model = "gpt-5.5"
model_reasoning_effort = "high"
notify = [
    "bash",
    "-lc",
    "afplay /System/Library/Sounds/Bottle.aiff",
]
personality = "pragmatic"
service_tier = "fast"

[features]
experimental_use_rmcp_client = true
js_repl = true
multi_agent = true

[marketplaces.openai-bundled]
last_updated = "2026-05-05T18:55:06Z"
source_type = "local"
source = "/Users/danielryan/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-05-04T12:22:54Z"
source = "/Users/danielryan/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"
source_type = "local"

[marketplaces.claude-plugins-official]
last_updated = "2026-05-05T18:55:06Z"
last_revision = "ac45fdae4b7af187b5624599ab054090dedadd94"
source_type = "git"
source = "https://github.com/anthropics/claude-plugins-official.git"

[mcp_servers.context7]
url = "https://mcp.context7.com/mcp"

[mcp_servers.linear]
url = "https://mcp.linear.app/mcp"

[mcp_servers.mobile-mcp]
args = [
    "-y",
    "@mobilenext/mobile-mcp@latest",
]
command = "npx"

[mcp_servers.playwright]
args = ["@playwright/mcp@latest"]
command = "npx"

[mcp_servers.chrome_devtools]
args = ["-y", "chrome-devtools-mcp@latest"]
command = "npx"
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."github@openai-curated"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."context7@claude-plugins-official"]
enabled = true

[plugins."frontend-design@claude-plugins-official"]
enabled = true

[plugins."imessage@claude-plugins-official"]
enabled = true

[plugins."browser-use@openai-bundled"]
enabled = true

[projects."/Users/danielryan/.codex"]
trust_level = "trusted"

[projects."/Users/danielryan/.dotfiles"]
trust_level = "trusted"

[projects."/Users/danielryan/Development/lexitales"]
trust_level = "trusted"

[projects."/Users/danielryan/Development/rising-sun"]
trust_level = "trusted"

[projects."/Users/danielryan/Development/rising-sun/backend"]
trust_level = "trusted"

[projects."/Users/danielryan/Development/rising-sun/web"]
trust_level = "trusted"

[projects."/Users/danielryan/Development/urban-interval-timer"]
trust_level = "trusted"

[projects."/Users/danielryan/Development/zerrtech/liferaft"]
trust_level = "trusted"

[shell_environment_policy]
inherit = "core"

[shell_environment_policy.set]
CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS = "1"
CLAUDE_CODE_NO_FLICKER = "1"
CLAUDE_CODE_SCROLL_SPEED = "3"
